[package]
name = "hb"
version = "0.3.0"
authors = ["Ryo Ota <nwtgck@nwtgck.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3", features = ["derive"] }
