name: CI

on: [push]

jobs:
  build_for_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: cargo test -- --color=always --nocapture
      - name: Release build
        run: |
          set -eux
          docker run --rm -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:1.50.0 sh -c 'sudo chown -R rust:rust . && cargo build --release'
          sudo chown -R $USER:$USER .
      - name: Operational test
        run: |
          set -eux
          sudo apt install -y pv
          seq 100 | pv -qL 50 | ./target/x86_64-unknown-linux-musl/release/hb -n 1 | ./target/x86_64-unknown-linux-musl/release/hb -d
      - name: Archive
        run: |
          set -eux
          mkdir hb-x86-64-linux
          cp target/x86_64-unknown-linux-musl/release/hb hb-x86-64-linux
          zip -r hb-x86-64-linux.zip hb-x86-64-linux
          tar czf hb-x86-64-linux.tar.gz hb-x86-64-linux
      - name: Upload Linux executables as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}-linux-artifacts
          path: hb-x86-64-linux.*

  build_for_mac:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: cargo test -- --color=always --nocapture
      - run: cargo build --release
      - name: Archive
        run: |
          set -eux
          mkdir hb-x86-64-apple-darwin
          cp target/release/hb hb-x86-64-apple-darwin
          zip -r hb-x86-64-apple-darwin.zip hb-x86-64-apple-darwin
          tar czf hb-x86-64-apple-darwin.tar.gz hb-x86-64-apple-darwin
      - name: Upload macOS executables as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}-mac-artifacts
          path: hb-x86-64-apple-darwin.*

  release_if_tag_exits:
    needs: [build_for_linux, build_for_mac]
    runs-on: ubuntu-20.04
    steps:
      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
      # NOTE: checkout is needed to use hub command
      - uses: actions/checkout@v3
      - name: Download the artifact (Linux)
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-linux-artifacts
      - name: Download the artifact (macOS)
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-mac-artifacts
      - run: ls -la
      # (base: https://github.com/actions/upload-release-asset/issues/28#issuecomment-617208601)
      - name: Release
        if: contains(github.ref, 'refs/tags/')
        run: |
          set -eux
          hub release create \
            -a hb-x86-64-linux.tar.gz \
            -a hb-x86-64-linux.zip \
            -a hb-x86-64-apple-darwin.tar.gz \
            -a hb-x86-64-apple-darwin.zip \
            -m "Release ${{ steps.extract_tag.outputs.tag }}" ${{ steps.extract_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
